# hybrid/systems_schema.py
"""Schema defaults for ship systems and subsystem health.

v0.6.0: Added heat management fields for all subsystems.
Heat is generated by system activity and dissipated passively.
Overheat conditions cause performance degradation or auto-shutdown.
"""

SUBSYSTEM_HEALTH_SCHEMA = {
    "power": {
        # Health settings
        "max_health": 120.0,
        "criticality": 5.0,
        "failure_threshold": 0.2,
        # v0.6.0: Heat settings (reactor generates and manages heat)
        "max_heat": 150.0,           # Maximum heat capacity (°C above ambient)
        "heat_generation": 2.0,      # Heat generated per kW output (°C/kW/s)
        "heat_dissipation": 3.0,     # Passive cooling rate (°C/s)
        "overheat_threshold": 0.85,  # Fraction of max_heat that triggers overheat
        "overheat_penalty": 0.5,     # Output multiplier when overheated
    },
    "propulsion": {
        # Health settings
        "max_health": 110.0,
        "criticality": 5.0,
        "failure_threshold": 0.25,
        # v0.6.0: Heat settings (main drive generates significant heat)
        "max_heat": 200.0,           # Drives run hot
        "heat_generation": 1.5,      # Heat per Newton-second of thrust
        "heat_dissipation": 2.5,     # Passive cooling rate
        "overheat_threshold": 0.90,  # Higher tolerance for drives
        "overheat_penalty": 0.6,     # Thrust reduction when overheated
    },
    "rcs": {
        # Health settings
        "max_health": 80.0,
        "criticality": 4.0,
        "failure_threshold": 0.2,
        # v0.6.0: Heat settings (RCS thrusters generate less heat)
        "max_heat": 80.0,
        "heat_generation": 0.5,      # Low heat per thruster pulse
        "heat_dissipation": 2.0,
        "overheat_threshold": 0.80,
        "overheat_penalty": 0.4,     # Torque reduction when overheated
    },
    "sensors": {
        # Health settings
        "max_health": 90.0,
        "criticality": 3.0,
        "failure_threshold": 0.2,
        # v0.6.0: Heat settings (active sensors generate heat)
        "max_heat": 60.0,
        "heat_generation": 0.8,      # Heat from active ping
        "heat_dissipation": 1.5,
        "overheat_threshold": 0.75,  # Sensors are heat-sensitive
        "overheat_penalty": 0.3,     # Range/accuracy reduction when overheated
    },
    "weapons": {
        # Health settings
        "max_health": 100.0,
        "criticality": 4.0,
        "failure_threshold": 0.25,
        # v0.6.0: Heat settings (weapons generate heat per shot)
        "max_heat": 120.0,
        "heat_generation": 5.0,      # Heat per weapon discharge
        "heat_dissipation": 2.0,
        "overheat_threshold": 0.85,
        "overheat_penalty": 0.0,     # Cannot fire when overheated (binary)
    },
}

# v0.6.0: Default heat values for subsystems not in schema
DEFAULT_HEAT_SETTINGS = {
    "max_heat": 100.0,
    "heat_generation": 1.0,
    "heat_dissipation": 1.5,
    "overheat_threshold": 0.80,
    "overheat_penalty": 0.5,
}


def get_subsystem_health_schema() -> dict:
    """Return default subsystem health schema."""
    import copy
    return copy.deepcopy(SUBSYSTEM_HEALTH_SCHEMA)


def get_heat_settings(subsystem: str) -> dict:
    """Return heat settings for a subsystem.

    Args:
        subsystem: Name of the subsystem

    Returns:
        dict: Heat settings (max_heat, heat_generation, heat_dissipation,
              overheat_threshold, overheat_penalty)
    """
    schema = SUBSYSTEM_HEALTH_SCHEMA.get(subsystem, {})
    return {
        "max_heat": schema.get("max_heat", DEFAULT_HEAT_SETTINGS["max_heat"]),
        "heat_generation": schema.get("heat_generation", DEFAULT_HEAT_SETTINGS["heat_generation"]),
        "heat_dissipation": schema.get("heat_dissipation", DEFAULT_HEAT_SETTINGS["heat_dissipation"]),
        "overheat_threshold": schema.get("overheat_threshold", DEFAULT_HEAT_SETTINGS["overheat_threshold"]),
        "overheat_penalty": schema.get("overheat_penalty", DEFAULT_HEAT_SETTINGS["overheat_penalty"]),
    }
