# hybrid/systems_schema.py
"""Schema defaults for ship systems and subsystem health.

v0.6.0: Added heat management fields for all subsystems.
Heat is generated by system activity and dissipated passively.
Overheat conditions cause performance degradation or auto-shutdown.
"""

SUBSYSTEM_HEALTH_SCHEMA = {
    "power": {
        # Health settings
        "max_health": 120.0,
        "criticality": 5.0,
        "failure_threshold": 0.2,
        # v0.6.0: Heat settings (reactor generates and manages heat)
        # Calibrated so normal load (~50kW) reaches ~40% heat at equilibrium.
        # Sustained overdrive or combat load can push into overheat territory.
        "max_heat": 150.0,           # Maximum heat capacity (°C above ambient)
        "heat_generation": 0.05,     # Heat per unit energy throughput (°C/kJ)
        "heat_dissipation": 3.0,     # Passive cooling rate (°C/s)
        "overheat_threshold": 0.85,  # Fraction of max_heat that triggers overheat
        "overheat_penalty": 0.5,     # Output multiplier when overheated
    },
    "propulsion": {
        # Health settings
        "max_health": 110.0,
        "criticality": 5.0,
        "failure_threshold": 0.25,
        # v0.6.0: Heat settings (main drive generates significant heat)
        # Formula: heat_amount = heat_generation * thrust_magnitude * dt
        # Calibrated for Epstein-class drives (up to 500 kN):
        # At full thrust (500,000 N): generation = 0.000005 * 500,000 = 2.5 °C/s
        # Dissipation: 2.5 °C/s — equilibrium at full sustained thrust.
        # Profile burns (10-50% throttle) generate 0.25-1.25 °C/s — well below
        # dissipation, so routine autopilot never overheats.
        # Overheat only occurs with damaged radiators, cascade effects,
        # or combat overdrive conditions — not routine flight.
        "max_heat": 200.0,            # Drives run hot
        "heat_generation": 0.000005,  # Heat per Newton-second of thrust (10x smaller for 10x thrust)
        "heat_dissipation": 2.5,      # Passive cooling rate (°C/s)
        "overheat_threshold": 0.90,   # Higher tolerance for drives
        "overheat_penalty": 0.6,      # Thrust reduction when overheated
    },
    "rcs": {
        # Health settings
        "max_health": 80.0,
        "criticality": 4.0,
        "failure_threshold": 0.2,
        # v0.6.0: Heat settings (RCS thrusters generate less heat)
        # Formula: heat_amount = heat_generation * torque_magnitude * dt
        # Typical attitude hold: ~50 Nm torque → 0.0005 * 50 = 0.025 °C/s (negligible)
        # 180° flip (multi-axis torque up to ~7300 Nm, ~12s):
        #   heat = 0.0005 * 7300 * 12 - 2.0 * 12 = 43.8 - 24 = 19.8 °C (well under 64°C)
        # Sustained evasive burns (45s+ of continuous manoeuvring):
        #   heat = 0.0005 * 7300 * 45 - 2.0 * 45 = 164 - 90 = 74 → overheat after ~35s
        # Normal flight (flips, attitude holds) should never overheat.
        # Only sustained combat evasion triggers the overheat penalty.
        "max_heat": 80.0,
        "heat_generation": 0.0005,   # Heat per Nm-second of torque
        "heat_dissipation": 2.0,
        "overheat_threshold": 0.80,
        "overheat_penalty": 0.4,     # Torque reduction when overheated
    },
    "sensors": {
        # Health settings
        "max_health": 90.0,
        "criticality": 3.0,
        "failure_threshold": 0.2,
        # v0.6.0: Heat settings (active sensors generate heat)
        "max_heat": 60.0,
        "heat_generation": 0.8,      # Heat from active ping
        "heat_dissipation": 1.5,
        "overheat_threshold": 0.75,  # Sensors are heat-sensitive
        "overheat_penalty": 0.3,     # Range/accuracy reduction when overheated
    },
    "weapons": {
        # Health settings
        "max_health": 100.0,
        "criticality": 4.0,
        "failure_threshold": 0.25,
        # v0.6.0: Heat settings (weapons generate heat per shot)
        # Calibrated so a full torpedo salvo (12 x 15 = 180 heat) requires
        # brief pauses, and a missile salvo (8 x 8 = 64 heat) is
        # sustainable with minimal waiting. Dissipation at 3.0/s means
        # 34s to cool from overheat threshold to zero.
        "max_heat": 120.0,
        "heat_generation": 5.0,      # Heat per weapon discharge
        "heat_dissipation": 3.0,     # Passive cooling rate (raised from 2.0)
        "overheat_threshold": 0.85,
        "overheat_penalty": 0.0,     # Cannot fire when overheated (binary)
    },
    "reactor": {
        # Reactor (power generation) — distinct from power_management distribution
        # Reactor failure = total power loss, cascading to all systems
        "max_health": 130.0,
        "criticality": 5.0,          # Highest criticality: everything depends on power
        "failure_threshold": 0.15,   # Reactors are resilient but catastrophic when they fail
        "max_heat": 200.0,
        "heat_generation": 0.03,     # Heat per kJ generated
        "heat_dissipation": 3.5,     # Good passive cooling (radiators)
        "overheat_threshold": 0.90,
        "overheat_penalty": 0.4,     # Severe output reduction when overheated
    },
    "life_support": {
        # Life support — crew survivability
        # Failure doesn't immediately kill but crew performance degrades
        "max_health": 70.0,
        "criticality": 2.0,          # Lower criticality (not combat-critical)
        "failure_threshold": 0.2,
        "max_heat": 50.0,
        "heat_generation": 0.2,      # Minimal heat from environmental systems
        "heat_dissipation": 1.0,
        "overheat_threshold": 0.80,
        "overheat_penalty": 0.6,     # Reduced environmental control when overheated
    },
    "radiators": {
        # Radiator panels — exposed heat rejection surfaces
        # Damage reduces ship's ability to radiate waste heat, causing
        # thermal buildup across all systems. Radiators are large, fragile,
        # and the most exposed subsystem on any ship.
        "max_health": 80.0,
        "criticality": 3.0,          # Loss causes cascading thermal crisis
        "failure_threshold": 0.15,   # Even damaged radiators help somewhat
        "max_heat": 40.0,            # Radiators themselves don't overheat much
        "heat_generation": 0.1,
        "heat_dissipation": 2.0,
        "overheat_threshold": 0.90,
        "overheat_penalty": 0.7,
    },
}

# v0.6.0: Default heat values for subsystems not in schema
DEFAULT_HEAT_SETTINGS = {
    "max_heat": 100.0,
    "heat_generation": 1.0,
    "heat_dissipation": 1.5,
    "overheat_threshold": 0.80,
    "overheat_penalty": 0.5,
}


def get_subsystem_health_schema() -> dict:
    """Return default subsystem health schema."""
    import copy
    return copy.deepcopy(SUBSYSTEM_HEALTH_SCHEMA)


def get_heat_settings(subsystem: str) -> dict:
    """Return heat settings for a subsystem.

    Args:
        subsystem: Name of the subsystem

    Returns:
        dict: Heat settings (max_heat, heat_generation, heat_dissipation,
              overheat_threshold, overheat_penalty)
    """
    schema = SUBSYSTEM_HEALTH_SCHEMA.get(subsystem, {})
    return {
        "max_heat": schema.get("max_heat", DEFAULT_HEAT_SETTINGS["max_heat"]),
        "heat_generation": schema.get("heat_generation", DEFAULT_HEAT_SETTINGS["heat_generation"]),
        "heat_dissipation": schema.get("heat_dissipation", DEFAULT_HEAT_SETTINGS["heat_dissipation"]),
        "overheat_threshold": schema.get("overheat_threshold", DEFAULT_HEAT_SETTINGS["overheat_threshold"]),
        "overheat_penalty": schema.get("overheat_penalty", DEFAULT_HEAT_SETTINGS["overheat_penalty"]),
    }
